version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run: echo "main"
  test:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
